create table if not exists public.permits (
  id bigint generated by default as identity primary key,
  city text not null,
  source text not null,
  source_id text not null,
  permit_number text not null,
  parent_permit text,
  address text,
  parcel_number text,
  zip_code text,
  neighborhood text,
  latitude double precision,
  longitude double precision,
  builder text,
  owner_name text,
  residential_type text,
  unit_count integer,
  applied_date timestamptz,
  issued_date timestamptz,
  finaled_date timestamptz,
  raw_status text,
  normalized_stage text,
  description text,
  is_new_residential boolean not null default false,
  source_url text,
  source_updated_at timestamptz,
  synced_at timestamptz not null default now(),
  raw jsonb,
  unique(city, source_id)
);

create index if not exists permits_city_idx on public.permits(city);
create index if not exists permits_stage_idx on public.permits(normalized_stage);
create index if not exists permits_zip_idx on public.permits(zip_code);
create index if not exists permits_applied_idx on public.permits(applied_date desc);
create index if not exists permits_newres_idx on public.permits(is_new_residential);

alter table public.permits enable row level security;

drop view if exists public.saturation_by_area;
create view public.saturation_by_area as
select
  city,
  coalesce(nullif(neighborhood,''), nullif(zip_code,''), city) as area,
  count(*) filter (where normalized_stage not in ('FINAL','CANCELLED')) as active_projects,
  sum(coalesce(nullif(unit_count,0),1)) filter (where normalized_stage not in ('FINAL','CANCELLED')) as active_units,
  sum(coalesce(nullif(unit_count,0),1)) filter (where normalized_stage in ('APPLICATION','REVIEW','APPROVED')) as preissue_units,
  sum(coalesce(nullif(unit_count,0),1)) filter (where normalized_stage in ('ISSUED','CONSTRUCTION')) as issued_units
from public.permits
where is_new_residential = true
group by city, coalesce(nullif(neighborhood,''), nullif(zip_code,''), city);
